branch-defaults:
  backend-zip-filename-fix:
    environment: love-u-convert-prod
environment-defaults:
  love-u-convert-prod:
    branch: null
    repository: null
global:
  application_name: love-u-convert
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
