branch-defaults:
  default:
    environment: love-u-convert-prod
    group_suffix: null
environment-defaults:
  love-u-convert-prod:
    branch: null
    repository: null
global:
  application_name: love-u-convert
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 24
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
